// src/data/ProjectData.js

export const projectData = [
  {
    id: 1,
    title: "FlashDash: Rider-Centric Delivery UI/UX",
    category: "UI/UX",
    description: "Optimized logistics interface designed for high-efficiency rider operations.",
    longDescription: "FlashDash is a high-fidelity UI/UX design focused on the daily challenges of delivery riders. The app features a high-contrast interface for outdoor visibility and streamlined order management to enhance efficiency.",
    images: ["delivery boy (2).png", "2.png", "3.png", "4.png"],
    link: "#",
    tech: ["Figma", "Mobile UI Design", "UX Research"],
  },
  {
    id: 2,
    title: "Smart Dairy: AI-Powered Livestock Care UX",
    category: "UI/UX",
    description: "Intelligent cattle management system for automated disease diagnosis and monitoring.",
    longDescription: "Smart Dairy is a comprehensive mobile solution designed for farmers to monitor cattle health. Includes AI diagnosis for Psoroptic Mange and multi-language support (English/Urdu).",
    images: ["hhhokm.png", "cvbnm.png", "plkmnbv.png", "poiuytrew.png", "wa.png"],
    link: "#",
    tech: ["Figma", "AI Integration UX", "Livestock Management"],
  },
  {
    id: 3,
    title: "Skylarks IT: Corporate Tech Solution UI",
    category: "UI/UX",
    description: "Modern web redesign focused on high-impact tech branding and performance metrics.",
    longDescription: "A high-impact website redesign aimed at positioning Skylarks as a leading tech solution provider. Features a dynamic services grid and performance metrics.",
    images: ["sss.png", "yyf.png", "ll.png"],
    link: "#",
    tech: ["Figma", "Web Design", "Corporate Branding"],
  },
  {
    id: 4,
    title: "Dollar Store: E-Commerce Marketplace UX",
    category: "UI/UX",
    description: "User-optimized retail interface for fast-paced digital shopping and bulk deals.",
    longDescription: "Optimized for quick browsing, featuring a comprehensive category system, daily deals, and bulk-buy options.",
    images: ["ml.png", "va.png", "5r.png", "098.png", "re.png"],
    link: "#",
    tech: ["Figma", "E-commerce UX", "Mobile UI"],
  },
  {
    id: 5,
    title: "Task Buddy: Service Marketplace UX",
    category: "UI/UX",
    description: "Professional freelancer platform featuring seamless task boards and user flow mapping.",
    longDescription: "Features a 'Task Buddy Board' for job listings, detailed post-creation flow, and professional profiles with project statistics.",
    images: ["oo.jpg", "g.png", "hh.png"],
    link: "#",
    tech: ["Figma", "Marketplace UX", "User Flow Mapping"],
  },
  {
    id: 6,
    title: "Drinks Cafe: Premium Tri-Fold Branding",
    category: "Marketing Design",
    description: "Clean typography and visual storytelling for premium beverage branding.",
    longDescription: "Designed for digital and print. Focuses on visual storytelling with high-quality photography and clean typography.",
    images: ["jj.jpg", "dr.jpg", "dr2.jpg"],
    link: "#",
    tech: ["Figma", "Graphic Design", "Branding"],
  },
  {
    id: 7,
    title: "Dollar Store: Promotional Retail Campaign",
    category: "Marketing Design",
    description: "High-impact retail banners designed for cross-platform marketing and engagement.",
    longDescription: "A series of high-impact digital banners designed for social media and web advertisements.",
    images: ["jn.jpg", "Cosmetic Banner.png", "Home Decor Banner.png", "Kid & Craft Banner.png"],
    link: "#",
    tech: ["Figma", "Marketing", "Retail Branding"],
  },
  {
    id: 9, // ID 8 is missing in your original list, keeping your sequence
    title: "Hair Bliss: Organic Social Media Campaign",
    category: "Marketing Design",
    description: "Engagement-driven Canva campaign for herbal hair care brand positioning.",
    longDescription: "High-engagement Instagram posts highlighting 100% herbal ingredients with direct WhatsApp integration.",
    images: ["llg.jpg", "loo.png", "pp.png", "jjjk.png", "5.png"],
    link: "#",
    tech: ["Canva", "Social Media Marketing", "Ad Creatives"],
  },
  {
    id: 10,
    title: "Dollar Shop Kamra: Localized Retail UX",
    category: "UI/UX",
    description: "Regional e-commerce UI design tailored for community-specific retail needs.",
    longDescription: "A dedicated UI/UX design project created in Figma for a local e-commerce solution in Kamra and Attock.",
    images: ["h3.jpg", "5r.png", "ml.png", "va.png"],
    link: "#",
    tech: ["Figma", "UI Design", "Prototyping", "User Research"],
  },
  {
    id: 11,
    title: "AI Email Assistant: Intelligent UX Dashboard",
    category: "UI/UX",
    description: "Figma-based AI dashboard design for smart mail management and contact exporting.",
    longDescription: "A high-fidelity Figma design for an AI Email Assistant featuring an automated dashboard and contact management.",
    images: ["lp2.jpg", "apa.png", "si.png", "si2.png", "ee.png", "ee2.png"],
    link: "#",
    tech: ["Figma", "User Flow Mapping", "AI Suggestion UX", "Contact Management"],
  },
  {
    id: 12,
    title: "AI Email Assistant: React Desktop Application",
    category: "Web Development",
    description: "Full-stack React application with Electron framework and real-time API integration.",
    longDescription: "A professional React-based web application that integrates email APIs to provide AI-powered features.",
    images: ["lg.jpg", "apa.png", "si.png", "si2.png", "ee.png", "ee2.png"],
    link: "https://github.com/summyia-fatima/ai-email-assistant",
    tech: ["React JS", "API Integration", "Tailwind CSS", "Electron framework"],
  },
  {
    id: 13,
    title: "Anjoma Zone: Secure Rental Checkout UX",
    category: "UI/UX",
    description: "Complex multi-step checkout flow using Auto-Layout 5.0 for secure transactions.",
    longDescription: "A comprehensive UI/UX project focused on simplifying the rental booking process with dynamic calculations.",
    images: ["lp.jpg", "p1.png", "p12.png", "p2.png", "p21.png"],
    link: "#",
    tech: ["Figma", "Auto-Layout 5.0", "Design Systems", "Prototyping"],
  },
  {
    id: 14,
    title: "Dollar Store: Category-Focused Print Design",
    category: "Marketing Design",
    description: "Vibrant tri-fold brochure design optimized for retail inventory categorization.",
    longDescription: "This project showcases a clean, category-focused layout for a discount store using a bright yellow color palette.",
    images: ["nn.jpg", "n2.png", "n3.png", "n4.png", "n5.png"],
    link: "#",
    tech: ["Figma", "Graphic Design"],
  },
  {
    id: 15,
    title: "Mamma’s Noodles: Mascot & Visual Identity",
    category: "Marketing Design",
    description: "Creative character-driven branding and mascot illustration for food marketing.",
    longDescription: "A creative branding project featuring a custom cat mascot illustration eating noodles.",
    images: ["cc.jpg", "cc2.jpg", "cc3.jpg", "cc4.jpg"],
    link: "#",
    tech: ["Figma", "Graphic Design"],
  },
  {
    id: 16,
    title: "Qmulate (Company Website) - Frontend",
    category: "Web Development",
    description: "Qmulate company website frontend built by converting Gulp code into Next JS and Tailwind CSS.",
    longDescription: "Developed by converting existing Gulp-based HTML structure into a modern Next.js application using Tailwind CSS.",
    images: ["q1 (10).jpg", "q1 (9).jpg", "q1 (8).jpg", "q1 (7).jpg", "q1 (6).jpg", "q1 (1).jpg"],
    link: "https://github.com/summyia-fatima/gulb-next",
    tech: ["Next JS", "Tailwind CSS", "GitHub", "Gulp to Next Conversion"],
  },
  {
    id: 17,
    title: "Twitter Clone",
    category: "Web Development",
    description: "Twitter clone built using React JS with Tailwind CSS and Firebase backend.",
    longDescription: "A fully responsive Twitter clone built with React JS and Tailwind CSS, powered by Firebase.",
    images: ["t3 (7).jpg", "t3 (6).jpg", "t3 (5).jpg", "t3 (4).jpg", "t3 (3).jpg", "t3 (1).jpg"],
    link: "https://github.com/summyia-fatima/my-twitter-clone/",
    tech: ["React JS", "Tailwind CSS", "Firebase"],
  }
];