// src/data/ProjectData.js

export const projectData = [
  {
    id: 1,
    title: "FlashDash: Rider-Centric Delivery UI/UX",
    category: "UI/UX",
    description: "Optimized logistics interface designed for high-efficiency rider operations.",
    longDescription: "FlashDash is a specialized logistics solution built to bridge the gap between complex dispatch data and real-time rider execution. \n\n Key Highlights: \n • High-Contrast UI: Designed for outdoor readability under direct sunlight. \n • Quick-Action Gestures: Minimized screen taps for order acceptance and navigation. \n • Live Tracking: Real-time route optimization to reduce fuel consumption. \n • Feedback Loop: Built-in rider rating and issue reporting system.",
    images: ["delivery boy (2).png", "2.png", "3.png", "4.png"],
    link: "#",
    tech: ["Figma", "Mobile UI Design", "UX Research"],
  },
  {
    id: 2,
    title: "Smart Dairy: AI-Powered Livestock Care UX",
    category: "UI/UX",
    description: "Intelligent cattle management system for automated disease diagnosis.",
    longDescription: "A revolutionary Agritech solution that empowers farmers with AI-driven insights for cattle health. \n\n Key Features: \n • AI Diagnosis: Visual recognition module for identifying Psoroptic Mange diseases. \n • Health Dashboard: Real-time monitoring of vaccination schedules and milk yield. \n • Accessibility: Dual-language support (English/Urdu) for local farmers. \n • Offline Sync: Critical data storage capabilities for areas with low internet connectivity.",
    images: ["hhhokm.png", "cvbnm.png", "plkmnbv.png", "poiuytrew.png", "wa.png"],
    link: "#",
    tech: ["Figma", "AI Integration UX", "Livestock Management"],
  },
  {
    id: 3,
    title: "Skylarks IT: Corporate Tech Solution UI",
    category: "UI/UX",
    description: "Modern web redesign focused on high-impact tech branding.",
    longDescription: "A high-impact website redesign aimed at positioning Skylarks as a leading global tech solution provider. \n\n Core Focus: \n • B2B Conversion: Lead generation forms integrated with a trust-building layout. \n • Interactive Grids: Dynamic service exploration using modern hover-state animations. \n • Branding: Consistent use of glassmorphism and premium dark-mode aesthetics.",
    images: ["sss.png", "yyf.png", "ll.png"],
    link: "#",
    tech: ["Figma", "Web Design", "Corporate Branding"],
  },
  {
    id: 4,
    title: "Dollar Store: E-Commerce Marketplace UX",
    category: "UI/UX",
    description: "User-optimized retail interface for fast-paced digital shopping.",
    longDescription: "Redefining the budget-shopping experience for the digital age with a focus on speed. \n\n Key Solutions: \n • Micro-Interactions: Smooth add-to-cart flows to enhance user satisfaction. \n • Advanced Filtering: Quick-access category system for browsing huge inventories. \n • Bulk-Buy Optimization: Dedicated flow for wholesale customers to manage large orders.",
    images: ["ml.png", "va.png", "5r.png", "098.png", "re.png"],
    link: "#",
    tech: ["Figma", "E-commerce UX", "Mobile UI"],
  },
  {
    id: 5,
    title: "Task Buddy: Service Marketplace UX",
    category: "UI/UX",
    description: "Professional freelancer platform featuring seamless task boards.",
    longDescription: "A community-driven marketplace connecting skilled freelancers with local tasks efficiently. \n\n Platform Features: \n • Task Buddy Board: A real-time bidding system for open job listings. \n • Profile Analytics: Visual statistics for freelancers to showcase project success. \n • Secure Messaging: Integrated chat system for safe client communication.",
    images: ["oo.jpg", "g.png", "hh.png"],
    link: "#",
    tech: ["Figma", "Marketplace UX", "User Flow Mapping"],
  },
  {
    id: 6,
    title: "Drinks Cafe: Premium Tri-Fold Branding",
    category: "Marketing Design",
    description: "Clean typography and visual storytelling for premium beverage branding.",
    longDescription: "A sophisticated branding project designed for both digital and print media. \n\n Design Strategy: \n • Visual Storytelling: Using high-quality photography to evoke premium taste. \n • Modern Typography: Clean font choices to maintain a minimalist luxury feel. \n • Layout Optimization: Precision-engineered tri-fold dimensions for professional printing.",
    images: ["jj.jpg", "dr.jpg", "dr2.jpg"],
    link: "#",
    tech: ["Figma", "Graphic Design", "Branding"],
  },
  {
    id: 7,
    title: "Dollar Store: Promotional Retail Campaign",
    category: "Marketing Design",
    description: "High-impact retail banners designed for cross-platform engagement.",
    longDescription: "A series of digital marketing assets designed to drive seasonal retail sales. \n\n Campaign Goals: \n • Visual Hierarchy: Highlighting discount percentages to grab immediate attention. \n • Cross-Platform Scaling: Banners optimized for Instagram, Facebook, and Web-headers. \n • Brand Consistency: Maintaining a vibrant yellow palette across all category banners.",
    images: ["jn.jpg", "Cosmetic Banner.png", "Home Decor Banner.png", "Kid & Craft Banner.png"],
    link: "#",
    tech: ["Figma", "Marketing", "Retail Branding"],
  },
  {
    id: 9, 
    title: "Hair Bliss: Organic Social Media Campaign",
    category: "Marketing Design",
    description: "Engagement-driven campaign for herbal hair care brand positioning.",
    longDescription: "Developed a comprehensive social media identity for an organic hair care brand. \n\n Content Strategy: \n • Educational Posts: Highlighting 100% herbal ingredients and benefits. \n • Call-to-Action: Direct WhatsApp integration for seamless order processing. \n • Aesthetic Harmony: Soft earthy tones to reflect the organic nature of the product.",
    images: ["llg.jpg", "loo.png", "pp.png", "jjjk.png", "5.png"],
    link: "#",
    tech: ["Canva", "Social Media Marketing", "Ad Creatives"],
  },
  {
    id: 10,
    title: "Dollar Shop Kamra: Localized Retail UX",
    category: "UI/UX",
    description: "Regional e-commerce UI design tailored for community-specific needs.",
    longDescription: "A dedicated UI/UX project focused on the hyper-local market of Kamra and Attock. \n\n Localized Features: \n • Regional Logistics: Shipping flows customized for local landmarks. \n • Trust-Building UX: Focus on cash-on-delivery and local pickup options. \n • Prototyping: Fully interactive high-fidelity prototype tested with local users.",
    images: ["h3.jpg", "5r.png", "ml.png", "va.png"],
    link: "#",
    tech: ["Figma", "UI Design", "User Research"],
  },
  {
    id: 11,
    title: "AI Email Assistant: Intelligent UX Dashboard",
    category: "UI/UX",
    description: "AI dashboard design for smart mail management and contact exporting.",
    longDescription: "Designed an AI-first dashboard to eliminate 'Inbox Fatigue' for corporate users. \n\n Smart Features: \n • Automated Triage: AI-categorization of emails into Priority and Social. \n • Contact Export: One-click extraction of email signatures into CRM formats. \n • Minimalist Workflow: Layout designed to keep users focused on high-value tasks.",
    images: ["lp2.jpg", "apa.png", "si.png", "si2.png", "ee.png", "ee2.png"],
    link: "#",
    tech: ["Figma", "AI Suggestion UX", "Dashboard Design"],
  },
  {
    id: 12,
    title: "AI Email Assistant: React Desktop Application",
    category: "Web Development",
    description: "Full-stack React application with Electron framework and API integration.",
    longDescription: "Developed a functional desktop companion for the AI Email Assistant system. \n\n Technical Implementation: \n • Electron Framework: Packaging the React app for high-performance desktop use. \n • API Orchestration: Seamless integration with Gmail and Outlook secure APIs. \n • State Management: Using React hooks for real-time inbox synchronization.",
    images: ["lg.jpg", "apa.png", "si.png", "si2.png", "ee.png", "ee2.png"],
    link: "https://github.com/summyia-fatima/ai-email-assistant",
    tech: ["React JS", "Tailwind CSS", "Electron framework"],
  },
  {
    id: 13,
    title: "Anjoma Zone: Secure Rental Checkout UX",
    category: "UI/UX",
    description: "Complex multi-step checkout flow using Auto-Layout 5.0.",
    longDescription: "A comprehensive UI/UX project focused on simplifying the rental booking process. \n\n Key Solutions: \n • Dynamic Calculations: Real-time price updates during date selection. \n • Auto-Layout 5.0: Highly responsive design components for all screen sizes. \n • User Friction Reduction: Multi-step form broken into digestible, secure stages.",
    images: ["lp.jpg", "p1.png", "p12.png", "p2.png", "p21.png"],
    link: "#",
    tech: ["Figma", "Auto-Layout 5.0", "Design Systems"],
  },
  {
    id: 14,
    title: "Dollar Store: Category-Focused Print Design",
    category: "Marketing Design",
    description: "Vibrant tri-fold brochure design optimized for retail inventory.",
    longDescription: "A professional print project showcasing inventory organization for retail stores. \n\n Design Highlights: \n • Categorization: Clear visual segments for Home, Cosmetics, and Kids sections. \n • Color Psychology: Use of high-energy yellow to denote value and discounts. \n • Print-Ready: CMYK optimized layout with bleed-margin precision.",
    images: ["nn.jpg", "n2.png", "n3.png", "n4.png", "n5.png"],
    link: "#",
    tech: ["Figma", "Graphic Design", "Print Media"],
  },
  {
    id: 15,
    title: "Mamma’s Noodles: Mascot & Visual Identity",
    category: "Marketing Design",
    description: "Creative character-driven branding and mascot illustration.",
    longDescription: "Developed a unique visual identity for a food brand centered around a custom mascot. \n\n Creative Process: \n • Character Design: Custom cat mascot illustration to build brand affinity. \n • Packaging Concept: Integrating the mascot into a playful, vibrant color scheme. \n • Brand Voice: Fun and energetic aesthetic tailored for younger audiences.",
    images: ["cc.jpg", "cc2.jpg", "cc3.jpg", "cc4.jpg"],
    link: "#",
    tech: ["Figma", "Illustration", "Brand Identity"],
  },
  {
    id: 16,
    title: "Qmulate (Company Website) - Frontend",
    category: "Web Development",
    description: "Frontend built by converting legacy Gulp code into Next JS.",
    longDescription: "Modernized a legacy codebase to improve SEO and developer experience significantly. \n\n Process & Results: \n • Migration: Successfully moved from Gulp-based HTML to Next.js 14. \n • Performance: Leveraged Server-Side Rendering (SSR) for faster load times. \n • Tailwind CSS: Replaced custom CSS with utility-first classes for maintainability.",
    images: ["q1 (10).jpg", "q1 (9).jpg", "q1 (8).jpg", "q1 (7).jpg", "q1 (6).jpg", "q1 (1).jpg"],
    link: "https://github.com/summyia-fatima/gulb-next",
    tech: ["Next JS", "Tailwind CSS", "Modernization"],
  },
  {
    id: 17,
    title: "Twitter Clone",
    category: "Web Development",
    description: "Twitter clone built using React JS with Firebase backend.",
    longDescription: "A fully functional, responsive social media clone for real-time communication. \n\n Technical Stack: \n • Real-time Database: Powered by Firebase for instant tweet updates. \n • Authentication: Secure user login and profile management. \n • UI/UX: Pixel-perfect replication of the Twitter interface using Tailwind CSS.",
    images: ["t3 (7).jpg", "t3 (6).jpg", "t3 (5).jpg", "t3 (4).jpg", "t3 (3).jpg", "t3 (1).jpg"],
    link: "https://github.com/summyia-fatima/my-twitter-clone/",
    tech: ["React JS", "Tailwind CSS", "Firebase"],
  },
  {
    id: 8,
    title: "Dollar Store: Unified Brand Identity System",
    category: "Marketing Design",
    description: "Comprehensive visual identity and brand guidelines for a retail discount chain.",
    longDescription: "Developed a cohesive brand system to ensure consistency across digital and physical touchpoints for a high-volume retail brand. \n\n Brand Strategy: \n • Logo Evolution: Modernized the existing brand mark for better scalability on mobile app icons. \n • Color Systems: Established a 'Value-Driven' palette using high-contrast yellows and blacks to trigger consumer psychological 'deal' responses. \n • Typography: Selected robust, sans-serif fonts to ensure readability on large-scale outdoor shop signage and small mobile screens. \n • Brand Guidelines: Created a rulebook for icon usage, spacing, and photography styles.",
    images: ["5r.png", "ml.png", "va.png"], // Aap yahan apni pasand ki relevant images ke naam daal sakti hain
    link: "#",
    tech: ["Figma", "Adobe Illustrator", "Brand Strategy", "Visual Design"],
  },
];